### PR TITLE
Fx Pass and API additions

### PR DESCRIPTION
**Pull request by Z3nner**
Adds several new macros, some of which improve or replace existing effects, while the rest are for supporting new content.
Adjusted, tweaked, modified, retimed, tuned, gutted, remodeled most of the macros in the module.  Includes API adjustments from dodgepong for better maintainability and streamlining.

### CODE REVIEW

**Comment by Z3nner** [comment]
@cirrahn I wanted to thank you again for your work on Lancer Weapon FX.  Were nearing release and I've pushed this request to the main module.  I thought I'd ping you and offer an opportunity to review everything.

**Comment by cirrahn** [comment]
@Z3nner these are amazing! I cannot wait to use them in-game (especially the giant nukes). The overall level of quality is outstanding.

Thank you for giving me a chance to review. I have done some brief testing and this is what I found:

- the "Brood Siblings" macro uses `"jb2a.melee_attack.03.trail.greatsword"` which does not exist for me, whereas I do have `"jb2a.melee_attack.03.greatsword"` (note the missing `.trail`)
  - I am one version behind on JB2A (using 0.6.3 when 0.6.4 is current) so this might be a "me" problem. I cannot verify as their website <https://jb2a.com/> is returning a 500 error!
- for the macros which require `warpgate` (`ElectricExplodeOnClick`/`ExplodeOnClick`), which is not listed in the requirements, it could be good to put the following at the top of the script to avoid a silent crash:
  ```
  if (typeof warpgate === "undefined") return ui.notifications.error("This macro requires the Warpgate module to be installed!");
  ```
- the "MissilePinaka" macro crashes when targetting two tokens which are close together, or when targetting only one token
- since there are several manual macros now (and a lot of automatic macros!) it is cumbersome to find them all. It might be time to split the compendium into "Lancer Weapon FX" and "Lancer Weapon FX (Manual)"?

It would also be nice to resolve the failing Check. Is that a fault of the test, or does a clean re-build of the pack need to be done? 
From experience, Foundry will re-order compendium lines on world save (and maybe other events). If you return to the Setup screen in Foundry then build and commit the pack, does that resolve the diff?

**Comment by Z3nner** [comment]
I double checked Sequencer, and it shows the `.trail` address as correct. I'm also on 0.6.3. I don't have the paid module version or anything so I'm not sure what the story there is.  I liked the trail version better with the modifications I made, but if a bunch of people don't have it for some reason it might be better to go with the other animation.  I'll look into it.

I like the improvements to the warpgate macros.  Just the sort of thing I was looking for in order to make more like these.

I noticed the issue with the Pinaka Missiles, but the game text requires that their areas of effect not overlap anyway, so the issue only pops up when it's being used incorrectly...which, while not intended kind of works out in my non-developer mind.

I also liked separating the compendiums.  I was sort of just including the extra effects as "easter eggs" but they are much better in their own basket.

I fixed the loose hanging macros, turns out I had overwritten a little work I did to add the content from Dustgrave's NPCs.  The only two left hanging are Power Knuckle and Plasma Projector. Power Knuckle was left behind when I reassigned that effect to the default melee effect, but left the other one in case users wanted to change it. Plasma Projector can actually go in the manual compendium.  It's a fun combination of ridiculously large energy beam and absurd explosions.

I don't know what the check is that's failing, honestly.  I thought it was related to it being a branch, and not having a release, but I don't know.

**Comment by cirrahn** [comment]
I have made https://github.com/Z3nner/lancer-weapon-fx/pull/28 with some more fixes!

The `.trail` issue looks like a JB2A bug, I have created an issue here: https://github.com/Jules-Bens-Aa/JB2A_DnD5e/issues/16

I have been poking the Pinaka Missiles some more and have found that it can still crash frequently when two valid targets are selected, if their X or Y position match (if they are far apart but in the same hex row/column), and infrequently when any two valid targets are selected.
I think it would also be good if it did not crash when used on a single target, as the text of the weapon is "up to two [...] areas". 
To fix these issues, I have made the changes:

- If there are fewer tokens than the number of target locations, treat each token as its own target location. Lloyd's Algorithm clusters >k points into k clusters, so if we have <=k points, each point must logically be its own "cluster." This fixes the single-target use.
- When generating initial points to start the algorithm, ensure each starting point is unique. This fixes the frequent (when sharing a coordinate)/occasional (when not sharing a coordinate) crashes when targeting two valid tokens

The check is failing because the final two "manual" macros are not yet in the manual compendium. I have moved them in!

**Pull request merged**
